# 라이브러리 설치

In [1]:
!pip install numpy 

In [2]:
import numpy as np 

print(np.__version__)

2.1.1


In [4]:
# help(np)

In [5]:
num1 = [1, 2, 3]
num2 = [4, 5, 6]
#       5, 6, 9
num1 + num2

[1, 2, 3, 4, 5, 6]

In [6]:
num1_arr = np.array(num1)
num2_arr = np.array(num2)

num1_arr + num2_arr

array([5, 7, 9])

In [8]:
print(type(num1_arr)) 
# 속성, 메서드

<class 'numpy.ndarray'>


In [9]:
num1_arr.T

array([1, 2, 3])

In [10]:
num1_arr.data

In [11]:
num1_arr.dtype

dtype('int64')

In [12]:
num1_arr.shape

(3,)

In [13]:
num1_arr.ndim

1

In [14]:
num1_arr.max()

np.int64(3)

In [16]:
num1_arr = np.array(num1, dtype="int8")
num1_arr.dtype

dtype('int8')

## 배열 만드는 방법

In [6]:
# 기본적으로 다른 데이터 자료형으로 numpy 배열로 변환
# 배열 생성
print(np.ones(3))

[1. 1. 1.]


In [2]:
import numpy as np 
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [3]:
arr_zeros = np.zeros((3, 4))  # 3행 4열 배열
print(arr_zeros)

# 1로 채워진 배열 만들기
arr_ones = np.ones((2, 3))  # 2행 3열 배열
print(arr_ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# 1차원, 2차원, 3차원, 4차원...
print(np.ndarray(shape=(2,2,2), dtype=float, order='F'))

[[[6.23042070e-307 2.67020135e-306]
  [1.69121096e-306 1.78019082e-306]]

 [[4.67296746e-307 1.42413555e-306]
  [3.22646744e-307 1.37959740e-306]]]


In [5]:
arr = np.ndarray(shape=(2,2,2), dtype=float, order='F')
arr.shape

(2, 2, 2)

# 배열의 차원을 변경

In [12]:
import numpy as np

In [13]:
temp_arr = np.arange(16)
temp_arr.reshape(1, 2, 8)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]])

In [15]:
temp_arr = np.arange(16)
temp_arr.reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [7]:
a16 = np.array([1.333333], dtype = np.float16)
a32 = np.array([1.333333], dtype = np.float32)

print(a16/3)
print(a32/3)

NameError: name 'np' is not defined

In [16]:
arr = np.array([-1, 2, -3])
arr/0

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_12784\3465403327.py:2: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([-inf,  inf, -inf])

결측치
- Missing Values : 잃어버린 값
- nan : Not a Number, ==> 아직 정의되지 않은 숫자 의미

In [22]:
print(np.nan, type(np.nan))

nan <class 'float'>


In [23]:
print(np.inf, type(np.inf))

inf <class 'float'>


In [24]:
print(-np.inf, type(-np.inf))

-inf <class 'float'>


In [25]:
arr = np.array([-1, 2, -3])
print(arr + np.nan)
print(arr + np.inf)

[nan nan nan]
[inf inf inf]


# 인덱싱 & 슬라이싱

In [30]:
arr = np.arange(10)
arr[1:5]

array([1, 2, 3, 4])

In [36]:
arr = np.arange(10).reshape(2, 5)
arr[0][1]

np.int64(1)

In [43]:
arr = np.arange(10000).reshape(100, 100)
# arr[0:4][0:1]

In [45]:
arr = np.arange(4)
arr[:2]

array([0, 1])

In [47]:
arr = np.arange(20).reshape(4, 5)
arr[1:4, 2:5]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [48]:
arr[1:, 2:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [56]:
# arr[행, 열]
arr[1:, 3:]

array([[ 8,  9],
       [13, 14],
       [18, 19]])

# 브로드캐스팅 연산

In [8]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
a + b

array([2, 4, 6])

In [11]:
a = np.array([1,    2,     3])
            
b = 3.0
a + b

array([4., 5., 6.])