# 라이브러리 설치

In [1]:
pip install -r requirements.txt #(라이브러리명)

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not open requirements file: [Errno 2] No such file or directory: '라이브러리명'


In [2]:
#라이브러리 하나만 설치할 때
!pip install numpy(라이브러리명)

In [3]:
#라이브러리 불러오기(설치 후 불러오기 필수)
import numpy as np

print(np. __version__)

2.1.1


In [ ]:
# help(np)

In [8]:
num1 = [1, 2, 3]
num2 = [4, 5, 6]
#       5, 6, 9
num1 + num2
#numpy 안쓰고는넘 오래걸려
#result = [a + b for a, b in zip(num1, num2)]

#print(result)

[1, 2, 3, 4, 5, 6]

In [9]:
#numpy사용
num1_arr = np.array(num1)
num2_arr = np.array(num2)

num1_arr + num2_arr

array([5, 7, 9])

In [10]:
print(type(num1_arr))
#클래스 -속성/메서드

<class 'numpy.ndarray'>


In [12]:
num1_arr.data

In [13]:
num1_arr.dtype

dtype('int64')

In [14]:
num1_arr.shape

(3,)

In [15]:
num1_arr.ndim

1

In [16]:
num1_arr.max()

np.int64(3)

In [ ]:
# 우리 회사에서 주로 다루는 0원~백만원 미만
0~1000000

In [19]:
num1_arr = np.array(num1, dtype='int8')
num1_arr.dtype

dtype('int8')

# 배열 만드는 방법

In [21]:
#기본적으로 다른 데이터 자료형으로 numpy 배열로 변환
#배열 생성
print(np.ones(3))

[1. 1. 1.]


In [24]:
print(np.zeros(3))

[0. 0. 0.]


In [32]:
print(np.ndarray(shape= (2,2),dtype= float, order='F'))


[[0.00000000e+000 8.71412156e-312]
 [8.71412155e-312 8.71412156e-312]]


In [30]:
arr.shape #몇차원

NameError: name 'arr' is not defined

# 배열의 차원을 변경

In [39]:
temp_arr = np.arange(16)
temp_arr.reshape(4,2,2) #==>다 곱해서 16

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [42]:
a16 = np.array([1.333333], dtype = np.float16)
a32 = np.array([1.333333],dtype = np.float32)

print(a16/3)
print(a32/3)

[0.4443]
[0.44444433]


In [45]:
arr = np.array([-1, 2, -3])
arr/0

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_109112\3465403327.py:2: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([-inf,  inf, -inf])

결측치
- Missing Values -: 잃어버린 값
- nan: Not a Number, ==> 아직 정의되지 않은 숫자 의미


In [57]:
print(np.nan, type(np.nan))

nan <class 'float'>


In [49]:
print(np.inf, type(np.inf))

inf <class 'float'>


In [59]:
aree = np.array([-1, 2, -3])
print(arr + np.nan)
print(arr+np.inf)

[nan nan nan]
[inf inf inf]
